package com.bawei.wangchu0106.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.wangchu0106.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DAO".
*/
public class greenDaoDao extends AbstractDao<greenDao, Void> {

    public static final String TABLENAME = "GREEN_DAO";

    /**
     * Properties of entity greenDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, Long.class, "name", false, "NAME");
        public final static Property Price = new Property(1, String.class, "price", false, "PRICE");
    }


    public greenDaoDao(DaoConfig config) {
        super(config);
    }
    
    public greenDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DAO\" (" + //
                "\"NAME\" INTEGER," + // 0: name
                "\"PRICE\" TEXT);"); // 1: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, greenDao entity) {
        stmt.clearBindings();
 
        Long name = entity.getName();
        if (name != null) {
            stmt.bindLong(1, name);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, greenDao entity) {
        stmt.clearBindings();
 
        Long name = entity.getName();
        if (name != null) {
            stmt.bindLong(1, name);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public greenDao readEntity(Cursor cursor, int offset) {
        greenDao entity = new greenDao( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, greenDao entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPrice(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(greenDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(greenDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(greenDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
